commerce_payment.commerce_payment_gateway.plugin.adyen_onsite:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_account:
      type: string
      label: 'Merchant Account'
    client_user:
      type: string
      label: 'Client User'
    client_password:
      type: string
      label: 'Client Password'
    skin_code:
      type: string
      label: 'Skin Code'
    hmac:
      type: string
      label: 'HMAC key'
    shopper_locale:
      type: string
      label: 'Shopper locale'
    recurring:
      type: string
      label: 'Recurring'
    state:
      type: string
      label: 'State'
    default_payment_type:
      type: string
      label: 'Default payment type'
    use_checkout_form:
      type: string
      label: 'Use checkout form'
commerce_payment.commerce_payment_gateway.plugin.adyen_offsite_redirect:
  type: commerce_payment_gateway_configuration
  mapping:
    redirect_method:
      type: string
      label: 'Redirect method'
